# Site wide configuration

title:            Miguel Ángel Ballesteros
locale:           en_US
url:              https://maballesteros.com


# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Miguel Ángel Ballesteros
  avatar: mike_profile.jpeg
  bio: "Maker, using software to bring great ideas to life. Manager, empowering and developing people to achieve meaningful goals. Father, devoted to family. Lifelong learner, with a passion for generative AI."
  email: maballesteros@gmail.com
  disqus-shortname: maballesteroscom
  twitter: #username
  facebook: #username
  google:
    plus:
    analytics: UA-70834776-1
    verify:
    ad-client: ca-pub-9574473104723845
    ad-slot: 1699150010
  bing-verify:
  github: maballesteros
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: miguel-ángel-ballesteros-velasco-a1100565
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["sample", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

defaults:
  -
    scope:
      path: "_posts/blog"
    values:
      layout: "post"
      categories: ["blog"]
  -
    scope:
      path: "_posts/experiments"
    values:
      layout: "post"
      categories: ["experiments"]
  -
    scope:
      path: "_posts/projects"
    values:
      layout: "post"
      categories: ["projects"]
